import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Luxe-consult",
//   description: "Generated by create next app",
// };


export const metadata: Metadata = {
  title: {
    default: "Luxe Consult – Luxury Real Estate in Kenya",
    template: "%s | Luxe Consult", // used for per-page overrides
  },
  description:
    "Discover luxury homes, apartments, and commercial properties with Luxe Consult. Premium real estate in Nairobi and across Kenya.",
  keywords: [
    "Luxury Real Estate Kenya",
    "Houses for Sale Nairobi",
    "Apartments Nairobi",
    "Luxe Consult Properties",
    "Real Estate Kenya",
    "Luxury Apartments  Nairobi",
  ],
  authors: [{ name: "Luxe Consult", url: "https://luxe-consult.com" }],
  creator: "Luxe Consult",
  publisher: "Luxe Consult",

  openGraph: {
    type: "website",
    url: "https://luxe-consult.com",
    title: "Luxe Consult – Luxury Real Estate in Kenya",
    description:
      "Find your dream home with Luxe Consult. Luxury houses, apartments, and commercial properties in Kenya.",
    siteName: "Luxe Consult",
    images: [
      {
        url: "/og-luxe-logo.png", // ✅ create a nice banner image inside /public
        width: 1200,
        height: 630,
        alt: "Luxe Consult Luxury Real Estate Kenya",
      },
    ],
    locale: "en_US",
  },

  // twitter: {
  //   card: "summary_large_image",
  //   title: "Luxe Consult – Luxury Real Estate in Kenya",
  //   description:
  //     "Explore luxury homes, apartments, and commercial properties with Luxe Consult.",
  //   creator: "@luxeconsult", // change if you have Twitter
  //   images: ["/og-image.jpg"],
  // },

  metadataBase: new URL("https://luxe-consult.com"),
  alternates: {
    canonical: "https://luxe-consult.com",
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {/* <body className="flex flex-col min-h-screen"> */}
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
